### ISSUE TITLE
Addition of Grandchildren Inside Bus & Outside Bus to transit.buses

### ISSUE THREAD

**Issue by jayshao** [openooh/venue-taxonomy#12]
Outmoove suggests adding and replacing the Grandchild Buses with two new grandchildren categories, which targets difference audience within the bus, or at the street level.

**Comment by mowasfi7** [comment]
+1

**Comment by christiancollins11** [comment]
+1

**Comment by jayshao** [comment]
Would we want to genericize this to a pattern for... all vehicles? Buses, Taxis, Planes, Subway?

From a compatibility perspective - I assume we're talking about more leaf-nodes vs. creating a "great-grand-child" level of hierarchy?

I think that would look like: creating a parallel entry and clarifying that "Bus" is... inside a bus? The Children descriptions imply that "Displays located on the inside of city or intercity buses." - though there are then children including "Terminal" which break that :) But - in the interest of managing complexity and reserving future leaf nodes - perhaps "Bus" for example could be redefined to "Bus (Inside)" and a new "Bus (Outside)

**Comment by bruno8g** [comment]
+1

**Comment by bruno8g** [comment]
I agree that this should be applicable to most Child in the transit category - outside and inside. My preference would be to use Grandchild.

**Comment by jayshao** [comment]
added a pass for bus - if that looks good to others, we could try to genericise further
