### ISSUE TITLE
Introduce a 0 in front of parent types

### ISSUE THREAD

**Issue by Armitage35** [openooh/venue-taxonomy#126]
A minor inconsistency if you look from the outside is that children and grand children enums always start with a 0 whereas parent start with a 1. This means that the count of digits is not always the same depending on if you are looking to a transit to Government parent category (1-9) vs financial and residential (10-11).

This is a minor issue in edge cases where we are looking at the numbers of digits to determine the venue type. Not critical and certainly has a good reason but strange from the outside.

**Comment by jayshao** [comment]
I don't believe we should do this, as it would be a compatibility breaking change (though I don't disagree it's inconsistent)

**Comment by Armitage35** [comment]
I agree, this would cause a bunch of issues when running auctions.
