### ISSUE TITLE
Add: Retail -> Grocery -> Aisles

### ISSUE THREAD

**Issue by jayshao** [openooh/venue-taxonomy#13]
Outmoove suggests adding Aisles (defined as screens at the ends of Aisles or screens within Aisles) as a grandchild to retail.grocery.

**Comment by mowasfi7** [comment]
What other grandchildren would be there under retail.grocery?

**Comment by ndbabb** [comment]
+1. We have some inventory on our DSP that exists in "aisles". 

@mowasfi7, the two other grandchildren under retail.grocery are currently shop_entrance and check_out.

**Comment by mowasfi7** [comment]
Thanks @ndbabb somehow I missed that in the spec.

+1

**Comment by christiancollins11** [comment]
+1
