### ISSUE TITLE
Add: Leisure -> High-End Dining

### ISSUE THREAD

**Issue by jayshao** [openooh/venue-taxonomy#17]
Astral suggests adding High End Restaurants to differentiate between Casual Dining.

**Comment by mowasfi7** [comment]
+1

**Comment by jayshao** [comment]
Do we have examples of High-End restaurants with screens? Or is this an academic, completeness item?

**Comment by jayshao** [comment]
@mercurim do you remember the origin of this item?

**Comment by christiancollins11** [comment]
+1 assuming we can create a clear distinction between high-end and casual. Definitely see publishers trying to fit their inventory into the "high-end" bucket undeservedly.

**Comment by mercurim** [comment]
> @mercurim do you remember the origin of this item?

I can circle back with the originator of the request, but I believe the main source of screens in H-end restos was outside the washrooms in high-end restaurants / inside bathrooms.

Big distinction was the presence of a reservation. High-end restaurants utilize reservation systems, and it ought to potentially be written into a description if we move forward.

**Comment by jayshao** [comment]
I wonder if "Dining" is substantial enough to separate it from Leisure as a top-level category - but did not do that in this pass.
