### ISSUE TITLE
Add: Health and Beauty -> Salons -> Unisex / Men's / Women's Men's

### ISSUE THREAD

**Issue by ndbabb** [openooh/venue-taxonomy#22]

**Comment by mowasfi7** [comment]
+1

**Comment by christiancollins11** [comment]
+1, prefer this approach to https://github.com/openooh/venue-taxonomy/issues/48

**Comment by alwaystabs** [comment]
- Makes sense to add `barbershop` as it's a more specific representation. 
- Downvote the request to add "Women's Salons" - most salons are unisex these days, and if there are some that cater more to womxn can that not be identified with the help of audience demographics?

**Comment by bruno8g** [comment]
+1

**Comment by jayshao** [comment]
I think in summary - the majority consensus seems to be to add grandchildren to Salons for "Barbershop".

It seems like in general... there's also support for adding Women's salons to maintain parity - though perhaps if we branch into that category, it's worth making it 3 children:

* Barbershops
* Women's salons
* Unisex salons

?

**Comment by jayshao** [comment]
Added a simple list with unisex, men, women - was having trouble with if "barbershop" would necessitate other categories like "more full service" salon - but not sure this is the right distinction either - or that that isn't a desireable split
