### ISSUE TITLE
Update description for Retail > Dispensaries

### ISSUE THREAD

**Issue by ndbabb** [openooh/venue-taxonomy#25]
Proposed changes: 1) Remove the word "medicinal" to cover both medicinal and recreational dispensaries. 2) Prefer "cannabis" to "marijuana".

The description changes from "A store that sells and dispenses medicinal marijuana and CBD products" to "A store that sells and dispenses cannabis and CBD products"

**Comment by christiancollins11** [comment]
+1

**Comment by mowasfi7** [comment]
+1

**Comment by mercurim** [comment]
+1, can confirm via current projects this would be a welcomed change.
