### ISSUE TITLE
Expanded of mall definitions.

### ISSUE THREAD

**Issue by mmercuri-broadsign** [openooh/venue-taxonomy#36]
From Simon team:

First a little background on the shopping center industry.  
The ICSC (International Council of Shopping Centers) which is the trade organization that supports the industry tracks 10 distinct shopping center classifications across a total of 115,857 locations in the US.  These include Super Regional Shopping Center, Regional Shopping Center, Power Center, Neighborhood Center, Strip Mall, Themed Center, Lifestyle Center, etc..  The properties that are owned by the major developers including Simon, Westfield, Taubman, Brookfield, and Macerich primarily consist of Super Regional and Regional Shopping Centers.  For reference the total number of properties that fall into this group is less than 1% of the 115k total properties.  Furthermore news organizations tend to lump the entire industry together when talking about 'malls' and or 'retail.'  They tend to make general statements about retail and or shopping centers which usually do not apply when looking at the large upscale super regional shopping centers.  

It is for these reasons that when defining the shopping center venue type it is important that we make a distinction between the Super Regional / Regional shopping centers and all of the others.  Shopping Centers like King of Prussia, Short Hills, Garden State Plaza, Roosevelt Field, etc should have a distinct

Regional Shopping Center: A large building or series of connected buildings typically containing over 50 retail stores, restaurants, movie theater, hotel, etc.: 205: retail.regional_shopping_center

Strip Mall: Attached row of stores that typically include grocery or big box stores, small shops, and food options. :206 : retail.strip_mall

**Comment by jayshao** [comment]
I am not entirely sure this makes sense. A "Super/Regional Shopping Center" seems like it's exceptional, and fairly well-known. E.g. their audience counts will be way higher, and they're more likely to be "asked for by name". This feels a little like sorting by "small, medium, large" - do we think buyers are likely to block or target by category only small/large? If they are targeting large, I would expect you'd see other approaches than venue categorization - e.g. the equivalent of a site-list, or geo-fences or the like. This seems to complicate the taxonomy for a small number of edge-cases

Strip Mall does seem like it might be interesting pulling out if buyers perception is different of the experience there vs. a... "mall mall?" Indoor/Pedestrian mall I suppose?

"Themed Center" seems... interesting - though I would think buyers would be more interested in what the theme was :) and that might be best handled by having something like "shop" under other categories like we do for Airports for instance - which while in many ways they resemble shopping malls, have a strong theme tying them together and influencing shoppers context and frame of reference

**Comment by bruno8g** [comment]
I also feel splitting by size of a mall adds little value.
Are Strip Mall screens outside, if front of the mall? This might be different and could be a grand child.

**Comment by jayshao** [comment]
I'm going to mark this as closed - though open to re-open if others feel this is worthwhile putting in the venue taxonomy (vs. assuming people will pull in other data)
