### ISSUE TITLE
Update Description: Residential -> Apartment Buildings to include Condominiums

### ISSUE THREAD

**Issue by dpaa-committee** [openooh/venue-taxonomy#44]
Parent: Residential – Child: Apartments Buildings
We’d like to include condos in the Child naming description so it says “Apartment Buildings/Condominiums”.

(Submission from Captivate via DPAA)

**Comment by jayshao** [comment]
All of those seem straightforward and value-add to me (with the comment I think we should preserve the "string value" names for compatibility and just change the descriptions/names

**Comment by jayshao** [comment]
Split into multiple issues for each change
