### ISSUE TITLE
Represent "Gas Stations" as "Convenience Stores" as a child

### ISSUE THREAD

**Issue by dpaa-committee** [openooh/venue-taxonomy#45]
A few concerns specific to GSTV:

1.	100% of our Gas Stations have convenience stores on site.  If a buyer isn’t familiar with GSTV and they are using this taxonomy to uncover inventory for convenience, they will miss us.

2.	While a smaller concern, we don’t love the term Gas Pump and prefer “Fuel Dispenser.”

Here are three alternative options for the classification.  I think we prefer A or B.

a.	Retail -> Gas Stations & Convenience Stores -> Fuel Dispenser (Gas Pump)
b.	Retail -> Gas & Convenience -> Fuel Dispenser (Gas Pump)
c.	Retail -> Convenience Stores -> Fuel Dispenser (Gas Pump)

**Comment by jayshao** [comment]
Splitting this into 2 issues for discussion

**Comment by jayshao** [comment]
While I recognize this is blurry - I think this might be a question for whether Brands perceive these the same, or want a differentiation. (Though - how do you decide to draw the line... say a WaWa that happens to sell gas - vs. a Gas station with a vending machine and coffee maker?)

@mowasfi7 @ndbabb curious if you have any insights? I'll see if I can get some media sellers to weigh in

**Comment by bruno8g** [comment]
Some countries are calling this category Petrol Stations. Maybe not changing the category name but it can be added to the definition (I understand localization is complex). Not exactly the comment but linked to it if we make a change.

**Comment by jayshao** [comment]
Marking this as help wanted - I think this could be worth having some Brand or Demand-side thinking about... how do they view these audiences and categories

**Comment by christiancollins11** [comment]
More of a supply perspective, but I'm -1 to the three proposals from GSTV.  I think it's a mistake to tie gas stations to convenience stores at the child level. All the other child categories are describing distinct places that are the primary venue in which a screen in located. This touches on the "nearby" or "secondary" venue type that we discussed, which I'm not entirely sold on, but open to discussing for a future version. 

Separately I don't think our job is to worry about cases where a buyer might want something like convenience stores and not be prompted to also think about gas stations. Convenience stores exist without gas stations and can serve an independent purpose for targeting.

**Comment by jayshao** [comment]
Marking this as closed based on discussion - on the assumption that people will choose the most appropriate category based on the screen placement. Open to re-opening if anyone (esp. on the demand side) has strong feelings
