### ISSUE TITLE
Remove "spas"

### ISSUE THREAD

**Issue by dpaa-committee** [openooh/venue-taxonomy#47]
Someone suggested the removal of the spa category, I dont know of any DOOH spa networks now that Rouge media dissolved that network but i could be missing some that I'm not aware of. FYI 
-Noah

(Rouge via DPAA)

**Comment by jayshao** [comment]
Not currently having any instances to me doesn't seem to be enough reason to remove a category from the taxonomy from a compatibility perspective - unless we are sure that thing will not come up in the future

**Comment by christiancollins11** [comment]
-1, if we agree that "spas" are a valid venue type, then see no reason to remove it

**Comment by mercurim** [comment]
-1, Spas are valid and I'm against removing valid categories

**Comment by bruno8g** [comment]
-1
