### ISSUE TITLE
Add "barbershops" as a child under "health and beauty"

### ISSUE THREAD

**Issue by dpaa-committee** [openooh/venue-taxonomy#48]
Can they add networks “barbershops”  as a child under parent of health and beauty. 

(Rouge Media via DPAA)

**Comment by christiancollins11** [comment]
This seems redundant with https://github.com/openooh/venue-taxonomy/issues/22, and I'd rather handle it by subcategory.

**Comment by ndbabb** [comment]
Agree with @christiancollins11 -- although perhaps a question as to whether "Men's Salon" and "Barbershops" are synonymous and which is a better term. @dpaa-committee, your thoughts?

**Comment by mowasfi7** [comment]
Agree. This should live under Salons.

**Comment by dpaa-committee** [comment]
@ndbabb The preference is "Barbershops"  thanks

**Comment by jayshao** [comment]
Duplicate #22

**Comment by jayshao** [comment]
I'm going to close this as a duplicate of #22
