### ISSUE TITLE
Rename "retail.gas_stations.pump" to use "Fuel Dispenser"

### ISSUE THREAD

**Issue by jayshao** [openooh/venue-taxonomy#52]
A few concerns specific to GSTV:

While a smaller concern, we don’t love the term Gas Pump and prefer “Fuel Dispenser.”

**Comment by jayshao** [comment]
This seems challenging from a compatibility perspective due to the "string value" being presumably machine-readable.

I *think* all current implementations actually use the IDs... if we were able to survey enough people I wonder if we could deprecate the "String Value" to allow for internationalization and future re-wording (as long as the semantics aren't changed, which I think would be the case in this case)

**Comment by christiancollins11** [comment]
Agreed. Vistar makes no use of the "string value" in integrations and would support deprecating.

**Comment by ndbabb** [comment]
Agree and support deprecating string values as well.

**Comment by mowasfi7** [comment]
Agree. Verizon Media uses IDs rather than string values.

**Comment by mercurim** [comment]
-1, can shed more light when I receive confirmation, but some DSPs consume string. I am in the process of getting them to look at the repo. There are use cases within Samsung where this value is needed.

**Comment by bruno8g** [comment]
Agreed to deprecate string values.

**Comment by jayshao** [comment]
@mercurim I think that if that's the case, if we "deprecate" that gives us the flexibility to not keep the strings in sync with the descriptions - or to announce some multiple release-cycle period when they might be removed (e.g. deprecated in 1.1, removed in... 1.3 or 1.4 towards the end of the year)

My worry is - with the strings, we will increasingly be caught in a case where the strings cannot match the descriptions if they change (or we have to have a lot of churn with deprecating and replacing categories) which I think makes them limited utility as we go forward.
