### ISSUE TITLE
Deprecate "string value" fields for future versions of the spec

### ISSUE THREAD

**Issue by jayshao** [openooh/venue-taxonomy#54]
This is a proposal to deprecate (or just remove) the "String value" components of the spec.

The current "String value" fields:
* create forwards compatibility challenges as names evolve
* make localization of the spec hard
* seem to have relatively small adoption vs. the numeric codes

**Comment by mowasfi7** [comment]
+1

**Comment by christiancollins11** [comment]
+1 per comments on other threads

**Comment by bruno8g** [comment]
+1

**Comment by jayshao** [comment]
This issues was created as part of discussion against #52 around renaming categories

**Comment by jayshao** [comment]
Notes from https://github.com/openooh/venue-taxonomy/discussions/49

* some implementors are using string fields as part of their implementation
* we don't want to suddenly cutoff something when it's being used
* what happens when labels change? renames / localization?
* should OpenRTB be machine-to-machine
* could announce, but target removal towards the end of the year? (1.3? 1.4?)
* alternative: change the semantics of the spec to pass human-readable, but not guarantee machine parse-ability and compatibility

Proposal: Deprecate string values with removal in 1.4 (+8. -1)
