### ISSUE TITLE
Proposal : Flatten the heirarchy and allow multiple venue types for any asset

### ISSUE THREAD

**Issue by ericlucit** [openooh/venue-taxonomy#55]
These are a few of my thoughts on strict category tree classifications and why they seldom work in practice.   My interest is from the DSP perspective.

If you review some of the issues related to the taxonomy, many of them boil down to naming and correctly assigning an asset to a specific category.  And because it is a tree based structure, an asset can only exist within a single node of that hierarchy

My question is this : Is this realistic and can we always assign an asset to only a single node?  and further more, is this future proof?

Is it a gas station, a convenience store, or both? - Is it also a grocery store because they sell groceries? - Who defines what exactly a grocery store is?  Is there a worldwide agreed upon definition of a convenience store?   Is the parking garage in a mall?? - Or is it in an office building??

When creating a strict single-node based structure, we are forced to define what a grocery store is and is not, and does this meet the definition of the sign owner, the grocery store owner, and the buyer and do they all agree on what that definition is?

I propose that the taxonomy is flattened to Parent, Child and there are lots of children, and a venue can be assigned to 1 or more nodes within that taxonomy.   Think of it more like tagging.     There is a reason why Amazon and Ebay allow you to assign listings to multiple categories, because strict 1:1 category structures never really accomplish what they try to do - classify the inventory - This breaks down when inventory is more than one class.

This solves the entire : "Is a gentlemans club a bar?" -  Because you can assign it both.   And buyers can then, when bidding, bid on all bars - OR, bid on all bars excluding gentlemans clubs - Or maybe just bid on all bars in Airports, etc.

The system would become much more flexible to the real-world if an asset, could be assigned to multiple nodes.

**Comment by christiancollins11** [comment]
While the reasoning behind the proposal makes sense, I'm very hesitant to adopt this approach in practice:

1. In this scenario, the incentive for media owners becomes to make the case that their inventory fits into as many buckets as possible to maximize the possibility of being targeted (think SEO-style). The taxonomy's job is to accurately characterize the environments in which ads are serving. Tricky cases can be addressed through sub-divisions where appropriate, which is the subject of a number of the proposals we're reviewing within this upcoming version. 
2. While targeting would likely be fine out of the box, 1:many will make any reporting/planning tool that groups by venue type very confusing to use. The question of how many impressions did I serve and to which venue types will not have a straightforward answer.
3. In cases where a media owner feels the value of their inventory isn't being truly represented, the media owner always has the option to build a PMP that conveys their unique value prop. 

In general, I think the outcome of this change would add a lot of future support complexity when the underlying issue could otherwise be addressed through better categorization.

**Comment by mercurim** [comment]
Spoke with Ads team, and my main concern is with points 1-2 from @christiancollins11 . One grandchild is deterministic for both buyer and seller, which is what I believe we should strive for. With clear descriptions, there shouldn't be ambiguity in the screen setting. 

That being said, I expect as adoption of this spec increases, media owners will be incentivized to disingenuously select venue types not by the descriptions, but by which category gives them a claim to a higher CPM (see ex: High-End restaurants vs QSR).

**Comment by bruno8g** [comment]
This suggestion could be reassessed later, after specs are adopted and widely used. I feel 1:many might create more confusions than help.

**Comment by ericlucit** [comment]
I think both of the concerns Christian brings up make sense and each one would need a series of solutions in order to make this proposal viable.

**Incentives to Categorize**
- What is the current process to audit screens and the categories they are assigned to?
- If a media owner mis-categorizes an asset, is there a process to appeal?
- I posit that this would have the opposite effect, i.e., If an asset is tagged as mall, grocery store, and convenience store, and a campaign is targeting all mall screens that are NOT convenience stores, will I get the desired screens?  And what would be the effect of this on the way that a media owner tags their screens?

**Reporting**
- Agreed that the true `sum-of-all-impressions` will be less than the `sum-of-impressions-per-tag`
- This would require a big lift in how analytics are presented, which may or may not be viable

Definitely a longer term discussion, and maybe some hybrid is developed where for any asset you have 2 fields

- Category  - e.g. 'Bar`
- Additional `tags` Gentlemans Club`, Sensitive`

**Comment by jayshao** [comment]
This was discussed during the 1.1 release call: https://github.com/openooh/venue-taxonomy/discussions/49

For the 1.1 draft, the feeling is that we will clarify that the current spec expects publishers to tag a given request with a singular venue. Having said that, the anticipation is that we will push a draft for a pubic comment period during the month of March, which is an opportunity to run through broader cases and see if there is strong community support for different conventions in the vein of a "2.0" rethinking of the spec, vs. continued evolution of the current, hierarchical approach

`invalid` is used as a tag consistent with: https://github.com/openooh/venue-taxonomy/issues/62 from the default label set - but let me see if I can reset up the project to perhaps figure out wording closer to the current "considering rejecting"
