### ISSUE TITLE
Add "test screen" category

### ISSUE THREAD

**Issue by aurakoljonen** [openooh/venue-taxonomy#57]
We'd like to propose categorizing screens that are simply for testing purposes to:

- ensure that they are not accidentally targeted in production campaigns
- make it easier to identify these screens for testing

Having a separate parent category "Test screen" would be the most logical option.

**Comment by jayshao** [comment]
I think this is a bad pattern. In general I would think we as an industry have "test transactions" - but if you fork them off into a separate category, how do you test venue categorization for instance?

Test environments is something that AdTech does... poorly, but I think in most systems this is probably better expressed as either a test publisher, test advertiser (to make billing sane) or perhaps a test transaction (e.g. their is a seldomly/inconsistently used `test` flag in OpenRTB

**Comment by christiancollins11** [comment]
-1, this is the wrong place to designate that a screen is part of a test
