### ISSUE TITLE
Add "washroom" category

### ISSUE THREAD

**Issue by aurakoljonen** [openooh/venue-taxonomy#58]
A niche category but advertisers probably want to know if a screen is located in the restrooms of a venue.

I think it would make sense to have one grandchild category under the "entertainment" parent but which child should it be associated with? Should there be a separate (grandchild) category for women's and men's?

The current washroom inventory we have come across has been in restaurants, bars, movie theaters, and sports arenas.

**Comment by jayshao** [comment]
Curious: do we think the audience/context is sufficiently different? E.g. washroom is overwhelming vs. being in a "restaurant" or a "sporting arena" ? This seems like it would take us down the direction of most every node potentially needing a child-node for washroom.
