### ISSUE TITLE
Grandchildren missing descriptions

### ISSUE THREAD

**Issue by jayshao** [openooh/venue-taxonomy#59]
Hi all,

great work here! [Ströer ](https://www.stroeer.de/nc/aussenwerbung/werbemedien/kategorie/public-video/werbemedien/Product/list.html) will most likely adopt the new venue-taxonomy early 2021.
Since we sell a lot of mall assets as well I´d like to ask you for a more specific feedback on the mall grandchildren:

Grandchild Category | Category Definition | Enumeration ID | String Value |  Stroeer explanation
Concourse | TBC | 20501 | retail.malls.concourse | These screens are in hallways and at the escalators
Food Court | TBC | 20502 | retail.malls.food_court | These screens are in hallways at food courts
Spectacular | TBC | 20503 | retail.malls.spectacular | it this something like Ströer [Digital Dream](https://www.stroeer.de/nc/aussenwerbung/werbemedien/kategorie/public-video/produkt/digital-dream.html) ?

_Originally posted by @kroening-stroeer in https://github.com/openooh/venue-taxonomy/discussions/41_

**Comment by bruno8g** [comment]
Suggestions, using the above comments.

Concourse: A large open area within malls, including hallways and escalators
Food Court: A common area within malls where counters of multiple food vendors are located and common tables are available to eat.
Spectacular: Large and impactful screens at a prime location in a mall. It often utilizes special embellishments.

**Comment by jayshao** [comment]
Added a commit, mistagged against #12
