### ISSUE TITLE
Rename Child Gyms

### ISSUE THREAD

**Issue by jayshao** [openooh/venue-taxonomy#8]
Outmoove suggests renaming Child Gyms to Sports or Sports Exercise, as this will include sports clubs, tennis clubs, etc.

**Comment by mowasfi7** [comment]
-1

I think Gym should be its own entity and Sports Clubs can be a new entity.

**Comment by ndbabb** [comment]
Does the existing venue type `entertainment.sports.club_house` cover sports clubs / tennis clubs, etc?

I agree with @mowasfi7 that gyms should be isolated in some way as it's a common target for buyers.

**Comment by christiancollins11** [comment]
-1 for reasons the @mowasfi7 mentioned. Buyers should have the ability to target gyms on their own.
