### ISSUE TITLE
Roadside and Highway are missing from the JSON spec

### ISSUE THREAD

**Issue by VagabondOfHell** [openooh/venue-taxonomy#82]
![image](https://user-images.githubusercontent.com/3276362/120404167-c31a2e80-c313-11eb-8481-332a80ce077e.png)

**Comment by ericlucit** [comment]
I will have a look - thanks!

**Comment by ericlucit** [comment]
This is fixed by https://github.com/openooh/venue-taxonomy/pull/85/files
