### ISSUE TITLE
Update: Parent Entertainment to Leisure

### ISSUE THREAD

**Issue by jayshao** [openooh/venue-taxonomy#9]
Outmoove suggests renaming Entertainment into Leisure, which they believe captures the spirit of the listed Child categories better.

**Comment by mowasfi7** [comment]
+1

**Comment by ndbabb** [comment]
+1

**Comment by christiancollins11** [comment]
+1

**Comment by jayshao** [comment]
I think... I would really want to deprecate the "string value" field - since "for compatibility" I would recommend not changing those values... but that's super confusing all throughout the spec if they don't match...

**Comment by christiancollins11** [comment]
Agree on deprecating the "string value", allows us to treat names as labels rather than worrying about a breaking change every time we update naming. 

Assuming we do, +1 on Entertainment -> Leisure

**Comment by jayshao** [comment]
Split out a separate issue to track at:
https://github.com/openooh/venue-taxonomy/issues/54
