### ISSUE TITLE
Outdoor should not be a parent category..way too broad

### ISSUE THREAD

**Issue by transitdude** [openooh/venue-taxonomy#90]
instead there should be one for highways (bulletins) and street-level. also buses and taxi tops reach the same audience as bus shelters and urban panels and should be grouped together.

**Comment by jayshao** [comment]
This seems like it would be a major change... I'm not sure there is a lot of appetite for this kind of change

**Comment by jayshao** [comment]
While I agree with this comment in principle, in practice - I think we should close this at this time and re-visit if we decide to produce a compatibility breaking version of the spec
